version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password,
      - MONGO_INITDB_DATABASE=development
    volumes:
      - ./mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 9092:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    depends_on:
      - mongodb
